### ISSUE TITLE
Compiling: Filtering Unused Functions and Variables at Compile-Time

### ISSUE THREAD

**Issue by abgox** [AutoHotkey/Ahk2Exe#100]
When compiling an executable file (.exe), I've noticed that some functions, which are defined but not used, are still included in the generated .exe file. 
In certain situations, can we identify and filter out the unused functions or variables at compile-time to reduce the size of the generated executable file?
Of course, this is just a feature suggestion that you can consider.

**Comment by TAC109** [comment]
Unfortunately it is beyond the scope of Ahk2Exe to analyse the script to be compiled to automatically remove unused parts of the script.

However the user can indicate which parts are to be omitted from the compiled program by using the `;@Ahk2Exe-IgnoreBegin` and `;@Ahk2Exe-IgnoreEnd` [compiler directives](https://www.autohotkey.com/docs/v2/misc/Ahk2ExeDirectives.htm#IgnoreKeep).

Cheers
