### ISSUE TITLE
LoadScript can't be compiled in Exe

### ISSUE THREAD

**Issue by yzqiang** [AutoHotkey/Ahk2Exe#104]
I use LoadScript class in the [ahk2_lib](https://github.com/thqby/ahk2_lib). It works very well in AHK script mode. But when I compiled my script to Exe using Ahk2Exe, something will be wrong.
With the LoadScript.ahk in the Lib, the Exe can work well.
When I remove the Lib dir or LoadScript.ahk, there will be errors when I start Exe.
![5fc2550802ab6f1a32ea0a8b2fe69a0](https://github.com/AutoHotkey/Ahk2Exe/assets/1594490/2d39088e-07d1-47a5-b75f-ab9a1b683833)
I think the compile didn't include the dynamic script in or something.
Is there some possible way to solve the problem?
Thanks very much.

**Comment by TAC109** [comment]
It appears that you are using AHK_H, which uses its own version of Ahk2Exe. This is maintained by [thqby](https://github.com/thqby/Ahk2Exe). 

I see that you have also opened an issue at [thqby/ahk2_lib](https://github.com/thqby/ahk2_lib/issues/58) for this problem. You would be best to carry on pursuing this issue with thqby.

Cheers
