### ISSUE TITLE
Compile AHK V2

### ISSUE THREAD

**Issue by H5820121** [AutoHotkey/Ahk2Exe#107]
Is it possible to compile AHK V2 file to exe in such a way that it will run without the interpreter, so it will run faster?
Thanks!

**Comment by TAC109** [comment]
As has been stated recently in the forums, this has not been implemented.

However the interpreter already 'compiles' the source script prior to execution - see [here](https://www.autohotkey.com/docs/v2/misc/Performance.htm) for more details.

Additionally many built in functions call underlying Windows routines (which are machine code) to perform the appropriate function.

For repetitive routines which may be inefficient when written in AHK it is always possible to write these in another language such as C, and compile this to machine code to be included in the script source - see [here](https://www.autohotkey.com/boards/viewtopic.php?f=96&t=124173) for example.

Cheers

**Comment by H5820121** [comment]
Thank you @TAC109 for the detailed reply, but after all I think there is a
lack of a convenient and easy to use application, like Ahk2Exe, that will
convert an AHK file to machine code, if you will know such an application I
would greatly appreciate if you mentioned it here.

‫בתאריך יום א׳, 21 ביולי 2024 ב-2:25 מאת ‪TAC109‬‏ <‪
***@***.***‬‏>:‬

**Comment by TAC109** [comment]
Sorry, I do not know of any such application.

Cheers
