### ISSUE TITLE
Ahk2Exe gets stuck changing main icon

### ISSUE THREAD

**Issue by benmusson** [AutoHotkey/Ahk2Exe#108]
AutoHotkey version: `v2.0.12`
Ahk2Exe version: `Ahk2Exe1.1.37.02a0`

When running from a GitHub actions running (`windows-latest`), Ahk2Exe is getting stuck on the "Changing the main icon..." step.
It never completes or moves on. If I call it without the icon argument it works as expected. 

```
D:\a\SteamAutoLauncher\SteamAutoLauncher\._ahk\ahk2exe\ahk2exe.exe /silent verbose /in D:\a\SteamAutoLauncher\SteamAutoLauncher\SteamAutolauncher.ahk /icon D:\a\SteamAutoLauncher\SteamAutoLauncher\images\favicon.ico /compress 0 /base "D:\a\SteamAutoLauncher\SteamAutoLauncher\._ahk\installation\v2\AutoHotkey64.exe" /out "D:\a\SteamAutoLauncher\SteamAutoLauncher\SteamAutolauncher.exe"

Ahk2Exe Status: "D:\a\SteamAutoLauncher\SteamAutoLauncher\._ahk\installation\v2\AutoHotkey64.exe" added to 'Base file' list.
Ahk2Exe Status: Auto-including any functions called from a library...
Ahk2Exe Status: Changing the main icon...
```

**Comment by TAC109** [comment]
Hi @benmusson 

Could you try running the compile with the `/silent verbose` parameter removed. There may be an error message which is not being handled correctly.

Could you also provide the icon you are attempting to use in case this is relevant to the problem. I can then use this when testing here.

Many thanks

**Comment by benmusson** [comment]
Thanks for the reply!

> `/silent verbose` parameter removed.

If I remove that parameter, I don't get any console output (success or failure) 🤷🏻‍♂️.


> Could you also provide the icon you are attempting to use in case this is relevant to the problem. I can then use this when testing here.

Here are the icons I've been using. There is a folder of icons several icons that work, and a folder of several icons that hang. The icons that hang were all created by me, the ones that work were found elsewhere online. It's just weird that if I run Ahk2Exe locally all of the icons work.
[icons.zip](https://github.com/user-attachments/files/17124052/icons.zip)

Other things I've tried:

- I'm still running `Ahk2Exe v1.1.37.01c1` locally, so I tried the same version on the GHA runner with no luck.
- I've also tried using a `windows-2019` runner instead of `windows-latest` with no change (local machine is `W10 22H2`)

Best regards.

**Comment by benmusson** [comment]
Maybe also worth mentioning is that I'm running Ahk2Exe via PowerShell's `Start-Process`?

I've tried looking around in [IconChanger.ahk](https://github.com/AutoHotkey/Ahk2Exe/blob/master/IconChanger.ahk) but it's a bit beyond me.

**Comment by TAC109** [comment]
I am able to compile a test script directly using your 'not_working' icons without problems.

I'm not following how you are running Ahk2Exe. There is reference to a 'GitHub actions runner' which I don't understand. Could you supply more detail on how your compilation system works?

I can't trouble-shoot the issue unless I can duplicate the compilation problem you are experiencing.

Cheers

**Comment by benmusson** [comment]
👍🏻 Understood, seems like something is subtly wrong with my environment. 

I'll keep poking at it and try make a good minimum reproducible example to share. 

Thanks much!

**Comment by benmusson** [comment]
> I'm not following how you are running Ahk2Exe. There is reference to a 'GitHub actions runner' which I don't understand. Could you supply more detail on how your compilation system works?

I've been using https://github.com/nukdokplex/autohotkey-build to run `Ahk2Exe` in my repo to automatically create releases.

> something is subtly wrong with my environment

There is 100% it. By including `AutoHotkey64.exe` and `Ahk2Exe.exe` directly into my repo I can get all the icons working.
This is not an `Ahk2Exe` issue, it's a https://github.com/nukdokplex/autohotkey-build issue.

Closing. Thanks!!!

P.S. has there ever been interest in an official `Ahk2Exe` GitHub Action? I can see there are multiple community versions.
