### ISSUE TITLE
Any ongoing plan to go AHK v2?

### ISSUE THREAD

**Issue by Bunker-D** [AutoHotkey/Ahk2Exe#110]
If I'm not mistaken, it seems to be impossible to install `Ahk2Exe` without having AHK v1.* installed, as it is needed to compile `Ahk2Exe.ahk`.

Is there any ongoing plan to update `Ahk2Exe.ahk` to AHK v2, or include a v2 alternative? Or isn't it possible to directly provide a downloadable exe?

**Comment by TAC109** [comment]
> If I'm not mistaken, it seems to be impossible to install `Ahk2Exe` without having AHK v1.* installed, as it is needed to compile `Ahk2Exe.ahk`.

It is true that AutoHotkey v1.1 would be needed to be installed if it was desired to run the Ahk2Exe.ahk source code. 

However most users download and use Ahk2Exe.exe (which is available from [here](https://github.com/AutoHotkey/Ahk2Exe/releases)), in which case AutoHotkey v1.1 is not required on the users' system.
> 
> Is there any ongoing plan to update `Ahk2Exe.ahk` to AHK v2, or include a v2 alternative? Or isn't it possible to directly provide a downloadable exe?

When compiling V2 scripts via the [Dash](https://www.autohotkey.com/docs/v2/Program.htm#dash) Ahk2Exe.exe will be downloaded and installed automatically if it is not present on the users' system. This one version of Ahk2Exe is capable of compiling either V1.1 or V2 scripts, depending on the version of the Base file specified for the compile.

There are no plans to rewrite the compiler in v2 (or any other version) of AutoHotkey.

Cheers

**Comment by Bunker-D** [comment]
Thank you. I missed the location of the exe, which indeed make a rewrite not very relevant.
(Glad I asked before starting working at least. Sorry for the inconvenience.)
