### ISSUE TITLE
Add /icon# options to replace the other 4 embedded icons.

### ISSUE THREAD

**Issue by jshall** [AutoHotkey/Ahk2Exe#47]
Using `Properties`/`Change Icon` of a link to a compiled script I can see that there are 5 embedded icons.
- The 1<sup>st</sup> is the default tray icon and is replaced using `/icon` option.
- The 2<sup>nd</sup> is the one used to mark script files, but does not appear to be used for the tray icon.
- The 3<sup>rd</sup> is used when the hotkeys are `Suspend`ed.
- The 4<sup>th</sup> and 5<sup>th</sup> are used in place of the 1<sup>st</sup> and 3<sup>rd</sup> when `Pause`d.

It would be useful if each of these could be replaced independently through additional switches. (ex. `/icon1` for the 2<sup>nd</sup>, `/icon2` for the 3<sup>rd</sup>, &hellip;)

**Comment by joedf** [comment]
Although for multiple icon changes, it is usually handled by modifying the *.bin file.
I still think this is an interesting feature. 👍

**Comment by TAC109** [comment]
This request can be achieved by using the following compiler directives, therefore can be closed.

`;@Ahk2Exe-AddResource Icon.ico, 160    ; Replaces 'H on blue'`
`;@Ahk2Exe-AddResource Icon.ico, 206    ; Replaces 'S on green'`
`;@Ahk2Exe-AddResource Icon.ico, 207    ; Replaces 'H on red'`
`;@Ahk2Exe-AddResource Icon.ico, 208    ; Replaces 'S on red'`
