### ISSUE TITLE
Add option to specify options to MPRESS

### ISSUE THREAD

**Issue by trlkly** [AutoHotkey/Ahk2Exe#48]
Mpress has a bunch of command line options. It would be nice to be able to specify them with the compiler, instead of compiling the scripts without compression and then manually running MPRESS. 

This would be most useful in the UI, although it should also probably be available on the command line.  Just add a text box after the Use MPRESS option that can contain MPRESS parameters.

**Comment by joedf** [comment]
`/MPRESS` is already available as a command-line option.
Also, I have already added it in the help textbox.
https://github.com/fincs/Ahk2Exe/commit/a69c2bb8e0a5a554e0f5d84adc15823f84701eae
Cheers 👍

**Comment by trlkly** [comment]
Neither of these provide a method to pass options along to MPRESS. There is
no way to use, for example, "mpress -s" or "mpress -m".

I checked the source code, and the options sent to MPRESS are fixed. All
I'm asking is the addition of a text box to add custom MPRESS options.

**Comment by joedf** [comment]
Ahh, ok. Now, I see what you meant. You or I could make a pull request for some like:  
`/mpress "-m -etc..."`  
_i.e._ the options would be enclosed with quotes.

**Comment by trlkly** [comment]
That's not a bad idea for the command line. But I think it should also be in the UI as a small text box that you can fill in (or leave blank). 

And I can actually try working on doing it myself, but I didn't want to do that until I knew it was okay.

**Comment by trlkly** [comment]
I think I figured it out well enough. Here's my attempt.  I tested it on my computer to see that it worked. 
#49 

(I accidentally deleted a line in compiler.ahk that I didn't mean to, but I don't know how to fix that now that I've made the request.)

**Comment by TAC109** [comment]
If a user wishes to specify the parameters to Mpress or Upx, they can write a 'PostExec' program to run the compressor directly as part of the conversion process and call this with the 'PostExec' directive. (The built-in compression option should be turned off in this case.)

I recommend that this issue be closed.

**Comment by joedf** [comment]
Agreed, superseded by ahk directives. 👍
