### ISSUE TITLE
@Ahk2Exe-AddResource

### ISSUE THREAD

**Issue by HotKeyIt** [AutoHotkey/Ahk2Exe#50]
Docs http://fincs.ahk4.net/Ahk2ExeDirectives.htm say to use asterisk to specify resource type before file name but the code does not consider this and it works only without asterix: https://github.com/fincs/Ahk2Exe/blob/edge/Directives.ahk#L111

**Comment by joedf** [comment]
By asterisk you mean `*` or `@`???

-
Joe DF | Administrator at ahkscript.org
Manager at AutoHotkey Foundation LLC | joedf@ahkscript.org
http://ahkscript.org/joedf | https://www.linkedin.com/in/joedf
________________________________

**Comment by HotKeyIt** [comment]
'*', see docs :)

**Comment by joedf** [comment]
Whoops! I looked at the wrong section :b

**Comment by joedf** [comment]
Seems to be working as of at least https://github.com/AutoHotkey/Ahk2Exe/commit/33d35b9112b8b397f01a1ed8725b094726c4af40 👍
