### ISSUE TITLE
Unicode32-bit.bin does not exist?

### ISSUE THREAD

**Issue by Banayat** [AutoHotkey/Ahk2Exe#51]
It says "Unable to copy the appropriate binary file as AutohotkeySC.bin because said file does not exist:
\...\...\...\...\Unicode32-bit.bin 

Do you still want to continue?"
How to fix this?

Edit: Ok, I've found out it is originally be placed at 
%Program Files%\AutoHotkey\Compiler\AutoHotkeySC.bin

There has never been any "Compiler" folder. Maybe there was a problem during installation process.

**Comment by Lexikos** [comment]
The compiler folder is where the installer puts the compiler. If there is no Compiler folder, you probably chose not to install the compiler when you installed AutoHotkey (I guess you got Ahk2Exe from here or somewhere else, separately).

In any case, Ahk2Exe is functioning as intended.
