### ISSUE TITLE
Beta test report 1.1.30.03_Beta_8

### ISSUE THREAD

**Issue by JnLlnd** [AutoHotkey/Ahk2Exe#63]
Is this the right place to leave a beta test report?

Just to say that I tested  1.1.30.03_Beta_8 to compile my app [QAP](https://www.QuickAccessPopup.com) and everything worked well. My [AHK source file](https://raw.githubusercontent.com/JnLlnd/QuickAccessPopup/master/QuickAccessPopup.ahk) includes various Ahk2Exe directives:

;@Ahk2Exe-IgnoreBegin
...
;@Ahk2Exe-IgnoreEnd

;@Ahk2Exe-SetVersion 10.2.1
;@Ahk2Exe-SetName Quick Access Popup
;@Ahk2Exe-SetDescription Quick Access Popup (Windows freeware)
;@Ahk2Exe-SetOrigFilename QuickAccessPopup.exe
;@Ahk2Exe-SetCopyright (c) Jean Lalonde since 2013
;@Ahk2Exe-SetCompanyName Jean Lalonde

If this can help, is there anything I could test more specifically?

Thanks for taking the time to update this so useful tool. Nice job!

**Comment by TAC109** [comment]
Thanks for your report. We hope to get the enhanced Ahk2Exe into the official downloads soon.

**Comment by joedf** [comment]
Thanks @JnLlnd :+1:
Maybe test the command-line interface and errors.
Another thing could testing out the current `BinMod.ahk` extension.

**Comment by JnLlnd** [comment]
I can test the params. I can look in the source code but are the params documented somewhere else?

And I'll take a look at BinMode. I never used it. I'll see if I can use it to edit the class signature in the exe file. Actually, I change it in the file "Unicode 64-bit.bin" and "Unicode 32-bit.bin".

**Comment by joedf** [comment]
Here are the command line parameters:
```
/in infile.ahk
/out outfile.exe
/icon iconfile.ico
/bin AutoHotkeySC.bin
/compress 0 (none), 1 (MPRESS), or 2 (UPX)
/cp codepage
/ahk path\name
```

**Comment by TAC109** [comment]
The parameters are documented in the AutoHotkey.chm help file included in the beta .zip. From the top level right pane, go to 'miscellaneous topics' -> 'Convert a script to an exe' (in ‘table of contents').

**Comment by JnLlnd** [comment]
I tested the command-line parameters:

/in script_name: OK, tested with absolute and relative paths/out exe_name: OK, tested with absolute and relative paths

/icon icon_name: OK, tested with absolute and relative paths 

/bin file_name: OK tested with my custom .bin file

/cp codepage: OK tested with 1252 (ANSI file) and 65001 (UTF-8 NO BOM file), no issue 
> with an UTF-8 with BOM file, the /cp parameter was ignored - I think this is the desired behavior

/compress: tested with 0, 1 and 2 and the three files (using small or large script) had the same size (maybe something is missing in my setup - but I had no error message)

/mpress: same result as with /compress

/ahk file_name: OK tested with C:\Program Files\AutoHotkey\AutoHotkey.exe (although I don't understand the reason for this parameter)

I tested the error messages when resource files were missing. All good.

I also tested the "Unload" and "& Reload" buttons. Personally, I would name the second button "Unload & Reload" for more clarity.

When I find more time, I'll explore BinMode

**Comment by JnLlnd** [comment]
I did a quick test with BinMod using the example in the doc and got no error and the EXE file runs normally.

But when I tried with a replacement string too short (that should normally be padded according to the doc), compiling gives no error but the EXE file seems to [have a problem](https://i.imgur.com/74NiD63.png).

My test script:

  ;@Ahk2Exe-PostExec "BinMod.exe" "%A_WorkFileName%"
  ; ok ;@Ahk2Exe-Cont  "22.>AUTOHOTKEY SCRIPT<.DATA               "
  ;@Ahk2Exe-Cont  "22.>AUTOHOTKEY SCRIPT<.DATA TOO SHORT"
  MsgBox, HÉLLO Wôrld
  ExitApp

**Comment by TAC109** [comment]
JnLlnd wrote:

> /compress: tested with 0, 1 and 2 and the three files (using small or large script) had the same size (maybe something is missing in my setup - but I had no error message)

You need to have previously downloaded MPRESS.exe and/or UPX.exe and placed them in the 'Compiler' folder (where Ahk2Exe.exe lives). This is explained in the 'Compress' section of the help .chm. If you use the GUI and select a compression option where the appropriate .exe is not present, a warning is shown in the status area of the GUI. However for the CLI, id you specify /compress and the compression utility is not present, it is just skipped. 

I suppose a warning could be shown in this case.

> /mpress: same result as with /compress

See above.

> /ahk file_name: OK tested with C:\Program Files\AutoHotkey\AutoHotkey.exe (although I don't understand the reason for this parameter)

Yes, I was reluctant to add this parameter as I thought most users would find it confusing! It is to deal with the rare case when Ahk2Exe has not been placed in the correct folder. Ahk2Exe needs to make use of AutoHotkey.exe during the compilation process, and needs to be able to locate it. The description of this parameter in the .chm should explain this. Do you think this explanation could be improved?

> I also tested the "Unload" and "& Reload" buttons. Personally, I would name the second button "Unload & Reload" for more clarity.

I'll look into this.

**Comment by TAC109** [comment]
JoLlnd wrote:

> But when I tried with a replacement string too short (that should normally be padded according to the doc), compiling gives no error but the EXE file seems to have a problem.
> My test script:
> ;@Ahk2Exe-PostExec "BinMod.exe" "%A_WorkFileName%"
> ; ok ;@Ahk2Exe-Cont  "22.>AUTOHOTKEY SCRIPT<.DATA               "
> ;@Ahk2Exe-Cont  "22.>AUTOHOTKEY SCRIPT<.DATA TOO SHORT"
> MsgBox, HÉLLO Wôrld
> Exit

Yes, this is a quirk of the way the Autohotkey .bin code searches for the embedded script when run. it is necessary to pad out the replacement string in the parameter with spaces for a total of 19 characters in this situation. (There is a comment to this effect in the BinMod.ahk script.)

As BinMod.ahk is a generalised binary patching program, it is not possible to flag an error in this case. It is just obeying the parameters given.

**Comment by JnLlnd** [comment]
> You need to have previously downloaded MPRESS.exe and/or UPX.exe and placed them in the 'Compiler' folder (where Ahk2Exe.exe lives). This is explained in the 'Compress' section of the help .chm. 

Sorry I missed it. No issue then.

> Yes, I was reluctant to add this parameter as I thought most users would find it confusing!

I understand. Your call to decide if you keep it or not.

> It is necessary to pad out the replacement string in the parameter with spaces for a total of 19 characters in this situation. (There is a comment to this effect in the BinMod.ahk script.)

These two excerpts of the BinMod.ahk header about this seems contradictory:

Line 17
> ;  (Note: The "DATA" field must be space-filled for a total of 19 char here.)

Line 38
>  c) Simple string to replace matched string.
;        **If shorter than b, it will be padded with 0x00's.**

Personally, I would prefer to have BinMod do it for the user. Safer.

**Comment by TAC109** [comment]
Jean,
I've changed and enhanced the description of the examples in BinMod.ahk. I hope that the distinction between padding with spaces in example 1, and padding with 0x00's in example 2, is clearer now.

Regarding compression of the .exe, I've added a warning message if the appropriate utility (MPRESS/UPX) is missing. (If you feel like testing further, I've attached an updated Ahk2Exe_Beta_8a.zip to this reply.)

I'm not proposing to make any further changes at present.

I'd like to thank you for your time and effort for the detailed testing of Ahk2Exe!
Tom

[Ahk2Exe_Beta_8a.zip](https://github.com/AutoHotkey/Ahk2Exe/files/3827987/Ahk2Exe_Beta_8a.zip)

**Comment by JnLlnd** [comment]
> Regarding compression of the .exe, I've added a warning message if the appropriate utility (MPRESS/UPX) is missing. (If you feel like testing further, I've attached an updated Ahk2Exe_Beta_8a.zip to this reply.)

I tested the error message when using the /compress 1 if MPress is not installed. Good.

Thanks to both of you.
