### ISSUE TITLE
Cannot run Ahk2exe in parallel using Powershell threads because of `Util_TempFile()`

### ISSUE THREAD

**Issue by GozaRuu** [AutoHotkey/Ahk2Exe#66]
Powershell threads trying to run `ahk2exe` in the same time will sometimes encounter a lock file issue when getting a temporary file name from `Util_TempFile()`. This happens when 2 threads get the same name at the same time, resulting in failure of some of the threads in our build script.

https://github.com/AutoHotkey/Ahk2Exe/blob/940e56be8ed48138078ce5be44ba7fa63a643e7c/Compiler.ahk#L21

A solution to this would be using a `universally unique identifier (UUID)` library for generating temporary file names.

**Comment by TAC109** [comment]
@GozaRuu 
Thanks - I’ll take a look at it.
In the meantime, a circumvention would be to stagger the start times slightly in your powershell script.

**Comment by TAC109** [comment]
@GozaRuu 
I’ve made some adjustments in beta 9d available here. [https://www.autohotkey.com/boards/viewtopic.php?f=6&t=65095](url)

Work file names now include the compiled .exe name, and I’m using the performance counter to get greater separation over time.

Let me know if this cures this problem.

**Comment by GozaRuu** [comment]
@TAC109 
Thanks for the reply, 
I just tested this and i encountered a regression compared to the version we're using 1.1.30.03, and it's the fact that it doesn't recognise relative imports 
for example if we have this in a file

```
#Include ../utils.ahk
#Include ../logger.ahk
``
it will base itself on the installer's path and not find the relatively imported file, whereas the old version does this with no issues.

![Screenshot 2020-06-24 at 11 15 48](https://user-images.githubusercontent.com/20685164/85528488-3e576880-b60c-11ea-87bc-213c36f18b80.png)

**Comment by TAC109** [comment]
Thanks for your report.
I've released Beta 9f which should fix this error. See [https://www.autohotkey.com/boards/viewtopic.php?f=6&t=65095](url)
Could you confirm that this version works for you as we are expecting to include this version into the official AutoHotkey release very soon.
Cheers

**Comment by GozaRuu** [comment]
@TAC109 thanks a lot, works very well now.
I will be waiting for the official release

**Comment by TAC109** [comment]
Thanks for reporting back.
