### ISSUE TITLE
Directive PostExec: add `Silent` and `Hidden` 

### ISSUE THREAD

**Issue by joedf** [AutoHotkey/Ahk2Exe#67]
I wonder if maybe a `silent` and/or `hidden` parameter should be added to the `PostExec` directive, like the [`Run[Wait]`](https://www.autohotkey.com/docs/commands/Run.htm) command.
Currently if I simply do the following, it works fine and no errors (RC = 0, return code?) are thrown:
```ahk
;@Ahk2Exe-PostExec mpress.exe "%A_WorkFileName%", 0
```
... but if the executable is not found or returns a non-zero exit code, a error msgbox is shown. Since I simply want compression if it's available, it's okay if it fails. I do the following to allow it to fail silently.
```ahk
; Trick to use mpress and throw no error if not available
;@Ahk2Exe-PostExec cmd /c mpress.exe "%A_WorkFileName%" &rem, 0
```
Perhaps, there are other use cases where this could useful?
```ahk
;@Ahk2Exe-PostExec FailureIsOkay.exe "%A_WorkFileName%" , 0, 1, 1
```
Syntax being:
```ahk
;@Ahk2Exe-PostExec Program [parameters] [, When, Hidden, Silent]
```
So no console (or whatever program) window flashes, and fails silently. What do you think?

**Comment by TAC109** [comment]
I like your idea! 

However, I’d like to choose a different name to 'Silent' if possible. One idea I had was 'MaskErrors'.

We could also add 'WorkingDir' as the optional third parameter for completeness.

`;@Ahk2Exe-PostExec Program [parameters] [, When, WorkingDir, Hidden, MaskErrors]`

'WorkingDir' could default to the directory which contains Ahk2Exe.exe (as it does now), or could default to 'Program\\..' (the directory which contains 'Program'), which would be the desired directory in 99.99% of all cases. (I prefer this last default.)

What do **you** think?

**Comment by joedf** [comment]
All of that sounds good to me! And I think PostExec's default dir should probably be the to-be-compiled script's directory like you've explained above. 👍  I think `MaskErrors` is perhaps more descriptive and more accurate, another possibility is `IgnoreErrors`.

**Comment by TAC109** [comment]
> All of that sounds good to me! And I think PostExec's default dir should probably be the to-be-compiled script's directory like you've explained above.

What I’m suggesting is that the default be the directory that contains the program to be run by the PostExec directive. So if the directive specifies `C:\Utils\MyProgram.exe` as the program to run, then the default WorkingDir would be `C:\Utils\`.
> I think `MaskErrors` is perhaps more descriptive and more accurate, another possibility is `IgnoreErrors`.

That looks better. 👍

**Comment by joedf** [comment]
I see. That seems fine. My only concern would be running a program without a full path, relying on the PATH variable.

Say a user copies `mpress.exe` into System32, then only specifying `mpress` should suffice.

**Comment by TAC109** [comment]
The plan is to get the path of the program using Util_GetFullPath which calls GetFullPathName, which should work. (I’ll test this condition.)

**Comment by TAC109** [comment]
If this method of determining the working directory doesn’t follow the 'path' then the user can supply the correct working directory using the 3rd parameter.

**Comment by joedf** [comment]
I see, with `Util_GetFullPath()` it should work just fine then! 👍

**Comment by joedf** [comment]
Hmm... A thought just came to mind... ~a bit of devil's advocate... What if say a user wants to use some kind of resource modifying program like BinMod but in post execution which would likely be best done with relative paths, possibly modifying other files?

**Comment by TAC109** [comment]
> I see, with `Util_GetFullPath()` it should work just fine then! 👍

On further checking, GetFullPathName only resolves relative names to full path\names. It doesn’t access the file system unfortunately, so will not help here. So I’ll revert back to the usual definition of other WorkingDir parameters.  If the user wants a specific working directory they will have to supply in the WorkingDir parameter. The default will be the directory containing the running copy of Ahk2Exe.exe.

**Comment by TAC109** [comment]
> Hmm... A thought just came to mind... ~a bit of devil's advocate... What if say a user wants to use some kind of resource modifying program like BinMod but in post execution which would likely be best done with relative paths, possibly modifying other files?

Not sure what you mean here? Can you give some concrete examples?

**Comment by joedf** [comment]
I think mainly we just leave the workingdir unspecified or whatever it is now and for the RunWait command used, but allow it to specified.

As for my bad explanation, if A_ScriptDir can be used, it would be handy and make the problem irrelevant.

**Comment by TAC109** [comment]
I've made the changes we discussed. I've also updated the .chm file (attached). Would you like to check out these alterations?
[AutoHotkey.chm.zip](https://github.com/AutoHotkey/Ahk2Exe/files/4943180/AutoHotkey.chm.zip)

**Comment by joedf** [comment]
Double-checked the code and documentation: everything looks good to go!
