### ISSUE TITLE
Unable to copy error by command line 

### ISSUE THREAD

**Issue by rcmdnk** [AutoHotkey/Ahk2Exe#68]
I got an error when I tried to make exe by the command line:

    "C:\Program Files\AutoHotkey\compiler\ahk2exe.exe" /in my_script.ahk /out my_script.exe

Following message appeared on the popup:

    Error: Unable to copy AutoHotkeySC binary file to destination.

    Specifically:
    "C:\Users\user\AppData\Local\Temp\~Ahk2Exe~build\my_script~exe~511090884045458.tmp"

After I made `~Ahk2Exe~build` folder directly, the command succeeded.

The error is shown from version 1.1.33.00.
Version 1.1.32.00 does not show the error (and it seems the temporary file is different like `C:\Users\user\AppData\Local\Temp\~tempXXXXXXXX.tmp`)

The error does not occur when I use GUI and execute `convert` even at version 1.1.33.00 and later.

**Comment by TAC109** [comment]
Thanks for your report.

I’ll check it out and get back to you soon.

**Comment by TAC109** [comment]
I couldn’t find an error in the Ahk2Exe source that would cause this error message to be generated, so I took the liberty of checking your `rcmdnk/vim_ahk` app on GitHub.

I believe there is a mistake in `/build/build.bat` on line 23:
`"%AHKPath%\compiler\ahk2exe.exe" /in vim.ahk /out build/vim_ahk.exe` should be
`"%AHKPath%\compiler\ahk2exe.exe" /in vim.ahk /out build\vim_ahk.exe`

At version 1.1.33.00 of Ahk2Exe there was a change to include the exe name in the temporary work file name generated, to prevent possible problems when multiple compiles were run at the same time. While Windows helpfully translates `/` into `\` for file names, unfortunately AutoHotkey does not, giving rise to this error message.

Cheers

**Comment by rcmdnk** [comment]
Thanks!
The error disappeared if I change the path using `\` correctly.
