### ISSUE TITLE
Suggstion: Option to compile as console application

### ISSUE THREAD

**Issue by hi5** [AutoHotkey/Ahk2Exe#69]
How about a built-in option or directive to compile as console application?

**Scripts and code:**

>  **lexikos:** I have a request for an option: "Compile as console application."I think the uses are fairly obvious, but can elaborate if you need me to.The following (somewhat rudimentary) script can be used (via Run if desired) to change the subsystem of the AutoHotkeySC.bin file before the script is compiled. Ideally it would be used to modify Compile_AHK's temporary copy of the bin file rather than the original. Using it directly on a compiled script exe invalidates its checksum and prevents the script from working.
https://autohotkey.com/board/topic/21189-compile-ahk-ii-for-those-who-compile/page-20#entry316030

>  **lexikos:** You can use the script I posted _[above_] after compiling the script. If it doesn't work with Unicode/x64, use AutoHotkeyA32.exe (just to run the script I posted).
https://www.autohotkey.com/boards/viewtopic.php?p=144491#p144491

**Comment by joedf** [comment]
Yessir right here:
https://www.autohotkey.com/docs/misc/Ahk2ExeDirectives.htm#ConsoleApp

Issue:
https://github.com/AutoHotkey/Ahk2Exe/issues/14

**Comment by hi5** [comment]
Oops, missed it... :)
