### ISSUE TITLE
[gui] Default values for bin and compress

### ISSUE THREAD

**Issue by htcfreek** [AutoHotkey/Ahk2Exe#71]
The gui should have default values selected on first start. 

Affected settings: bin, compress

**Comment by TAC109** [comment]
I have tested this on my system and on first start `bin` shows `(Default)` and `Compress` shows `(none)`, which are the expected values. Could you provide more details of what you are seeing, please?

**Comment by htcfreek** [comment]
I would expect tgat bin shows the autohotkey version which is default on running scripts.
Compres csn be none.

I don't like the word "default" in the drop-down. Normal user don't know the associated value.

**Comment by TAC109** [comment]
When you install AutoHotkey for the first time you are asked to select the version required: Unicode 32 bit, Unicode 64 bit, or ANSI 32 bit. As a result of this selection the installer makes a copy of the appropriate AutoHotkey executable and renames it AutoHotkey.exe. This then becomes the default version that is run with your scripts.

In the same way, the installer, at the same time, makes a copy of the same selected version of the compiler's .bin file and renames the copy 'AutoHotkeySC.bin'. This then becomes the default version that can be selected when scripts are compiled.

So the idea here is that using the default .bin file, script can be compiled with the same version that was used to develop and debug the scripts when run interactively.

I hope this helps explain the reason for the 'Default' entry in the drop-down list.

**Comment by Wrongtown** [comment]
Makes sense to me.

I suppose a minor UX improvement could be to change the text to "Default (selected on install)" or similar?

Better would be the explicit value set during the install process (for example) "Unicode 64 bit (selected on install)".

**Comment by htcfreek** [comment]
> Makes sense to me.
> 
> I suppose a minor UX improvement could be to change the text to "Default (selected on install)" or similar?
> 
> Better would be the explicit value set during the install process (for example) "Unicode 64 bit (selected on install)".

That's what I mean.

**Comment by TAC109** [comment]
Commit 1ad8222 addresses this enhancement and will be included in the next release.

**Comment by TAC109** [comment]
I've created [Ahk2Exe v1.1.33.09_Beta_1](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=65095) which includes these recent changes.
