### ISSUE TITLE
[gui] Show list of ahk2exe directives

### ISSUE THREAD

**Issue by htcfreek** [AutoHotkey/Ahk2Exe#72]
The gui should have a second "expert" tab to show the ahk2exe directives found in script file.

As additional improvement it would be great ifvthe user can edit the directives and save them in the script.

The directives could be shown as list or table.

**EXAMPLE**
Directive | Properties
------------ | -------------
name1 | values
name2 | values

**Comment by TAC109** [comment]
Thank you for your suggestion. We are not planning on implementing this enhancement at present but will keep it in mind for the future.

**Comment by TAC109** [comment]
This task is more suited to a dedicated editor. There are no plans to implement this request.
