### ISSUE TITLE
Suggestion: Increase the visibility/awareness of using AHK portably

### ISSUE THREAD

**Issue by gaiking-uk** [AutoHotkey/Ahk2Exe#78]
**Intro note**
- Disclaimer: This isn't an "issue" but rather a suggestion I thought it might be helpful to make, following a discussion / gaining some useful info from Lexikos... Wasn't sure how best to submit this but hopefully an issue works
- Also, the post is written as "an appreciative user, who wants other users to fully appreciate the advantages/power of AHK (and to make sure that the work the team has done, doesn't go un-realised)" and hope it is received as such, however feel free to close if you don't think this change would be helpful

**Suggestion (Increase the visibility/awareness of using AHK portably)**
- `Website`: Add a portable download option to the AHK homepage
- `AutoHotKey.exe`: On the program home screen, increase the prominence of the "Why am I seeing this?" section / invert the paradigm, i.e. ...
  - Current: "Here is a load of useful info about AHK, btw did you know that you can use `AutoHotKey.exe` to run a script by supplying the script name [etc]"
  - Suggested: "You can use `AutoHotKey.exe` to run AHK scripts (and even copy the file from `C:\Program...` and run scripts without installing AHK [etc]... Since you're here though, here is a load of useful info abut AHK"

**Context**
- I have been using AHK for several years, but only realised in the last few days how truly portable it was (which is great)
- This new knowledge will result in me making a few changes to how I use/write AHK. Which is fine - I have no problem with this, but thought it might be helpful to raise the above in case any other users were in a similar position

**Comment by TAC109** [comment]
Thanks for your comments.
