### ISSUE TITLE
Sending unicode values resulting ��

### ISSUE THREAD

**Issue by luftaquila** [AutoHotkey/Ahk2Exe#79]
My autohotkey script to convert to exe has something like this:
```ahk
:*:wheart::♡
:*:bheart::♥
:*:wstar::☆
:*:bstar::★
:*C:ud`t::_
:*:wdt::⚬

:*:uarr::↑
:*:darr::↓
:*:larr::←
:*:rarr::→
:*:ularr::↖
:*:urarr::↗
:*:dlarr::↙
:*:drarr::↘
```

It works properly when running as ahk extension itself. But executable built from script via Ahk2Exe sends �� character instead of sending exact symbol. I tried all base files and compress mode including `v1.1.33.9 Unicode 64-bit binary`, but nothing changes. My AutoHotKey is also installed as 64-bit mode.

Thank you.

**Comment by JnLlnd** [comment]
Maybe your code editor is saving with ANSI encoding. Try saving with Unicode encoding.

**Comment by luftaquila** [comment]
> Maybe your code editor is saving with ANSI encoding. Try saving with Unicode encoding.

I just forgot to mention about encoding. It is UTF-8 and the .ahk before converting to exe sendㄴ unicode character correctly.

**Comment by TAC109** [comment]
Hi @luftaquila 

Could you double check the encoding of your script in your editor. It should be UTF8 **with BOM** (the last part is important).

Cheers

**Comment by luftaquila** [comment]
I have really no idea why, but Ahk2Exe follows with the default AutoHotKey installation(C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe) works while downloaded from this repo's release page dosn't work. Anyway, thanks for your help!
