### ISSUE TITLE
Critical Error "Invaild Memory ReadWrite" when trying to Compile with Windows Store Version

### ISSUE THREAD

**Issue by Hymian7** [AutoHotkey/Ahk2Exe#80]
I have the Windows Store Version of AHK installed in Version 1.1.33.09 and everytime I try to compile a Script to exe, I get an error as shown in the Screenshot below.

When I compile the same script with the portable version of ahk2exe, everything works fine.

![image](https://user-images.githubusercontent.com/38748117/123932969-3bffbb00-d992-11eb-83e0-00ed6d7c1cba.png)

**Comment by TAC109** [comment]
Thanks for your report. I am looking into this error and will get back to you.

Cheers

**Comment by TAC109** [comment]
I have test-compiled a few scripts with this Microsoft Store version of Ahk2Exe without getting any errors. 

Could you supply some more information on the script you are trying to compile? 
What is the full path and name of the script (the total length of the path and name as well)?
Have you been able to compile any other scripts successfully?

Any further information you can provide would be helpful. 

Cheers

**Comment by Hymian7** [comment]
Hi @TAC109,

I have now tested different cases and came to the conclusion, that the reason for the error must be the length of the full path.

The script under
C:\Users\de-lmoeller\Desktop\Reflexis Autohotkey\Test\12345.ahk

does compile successfully (63 chars path length) while the same script under

C:\Users\de-lmoeller\Desktop\Reflexis Autohotkey\Test\123456.ahk

throws the error (64 chars path length).

Best regards
Hymian7

**Comment by TAC109** [comment]
This error has been fixed in AutoHotkey version 1.1.33.10. Hopefully this will be published in the Microsoft Store soon.
