### ISSUE TITLE
1.1.34.00_Beta_2-4 bug ?

### ISSUE THREAD

**Issue by OlSoul** [AutoHotkey/Ahk2Exe#84]
Beta_2-4 Base File Display empty
Beta_1 OK

**Comment by TAC109** [comment]
Ahk2Exe finds its base files by searching its immediate environment as described in the updated documentation - see [here](https://www.autohotkey.com/docs/Scripts.htm#information) for details.

If, after checking this, there is still a problem please supply details of your AutoHotkey directory layout with file names, etc indicating where you have placed the downloaded Ahk2Exe.  (The dos `tree` command is useful for this.)

Cheers

**Comment by TAC109** [comment]
On examining this further, I see that there is a problem with the gathering of applicable .exe base files in the later beta releases. I’ll fix this soon.

**Comment by OlSoul** [comment]
Thank you. I'm looking forward to it.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 上午9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AutoHotkey/Ahk2Exe] 1.1.34.00_Beta_2-4 bug ? (#84)





 
On examining this further, I see that there is a problem with the gathering of applicable .exe base files in the later beta releases. I’ll fix this soon.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TAC109** [comment]
I've released Beta_5 with this fix:

- Include Ahk2Exe in 'Base file' list if relevant.

Hopefully, this fixes the problem you found.

**Comment by OlSoul** [comment]
Thank you.
