### ISSUE TITLE
Release v1.1.34.00_Beta_9b flagged as virus bij ApexOne

### ISSUE THREAD

**Issue by thomvil** [AutoHotkey/Ahk2Exe#86]
Unlike all the release before, that i've used, the latest release (v1.1.34.00_Beta_9b) is being flagged as:
TROJ_GEN.R06BC0PC422

I assume this is a false positive. But I've never run into this false positive before. The same AV does not flag the previous release as TROJ_GEN

**Comment by joedf** [comment]
What about installing AutoHotkey, and compile ahk2exe from source?
by dragging `Ahk2Exe.ahk` onto `Ahk2Exe.ahk` itself.

**Comment by TAC109** [comment]
There is no virus included in Ahk2Exe v9b. Many other users have downloaded it without it being flagged. As you are aware, the complete source is available for inspection, and you can compile it yourself by following the instructions in the 'Readme.MD' file, as suggested by Joedf.

You could help the community by advising your antivirus vendor that this is a false positive. 

Cheers

**Comment by superelitist** [comment]
I see this was closed, but I don't think this issue should be considered resolved, false positive or not. I was also impacted by this--Firefox didn't want me to download it. I know this is a beta, but being reported as malicious has the potential to impact product acceptance. May I suggest addressing this in your `README.md` so users know that you are at least aware of the issue?

VirusTotal reports that 23 out of 63 vendors flagged this release (although it wouldn't surprise me one bit if many of those vendors were just copy-catting), and unfortunately, I don't have the time to figure out how to contact every single one of them.

Last, what if this happens again? Are we sure this isn't something we need to worry about moving forward?
