### ISSUE TITLE
Signed executables cannot be used as base

### ISSUE THREAD

**Issue by Lexikos** [AutoHotkey/Ahk2Exe#88]
The _UIA exe files (for "Run with UI Access", created by the installer) are cryptographically signed, as required for the uiAccess manifest attribute to work. Modifying a signed executable invalidates its signature, and the result might be worse than a file with no signature. I vaguely recall that uiAccess=true might cause issues if some of the requirements aren't met (such as having a valid signature).

Regardless, listing the _UIA files as potential base files just adds noise to the list, with no benefit.

It would be acceptable to simply exclude the files by name. I've chosen to identify them that way in my own interpreter-selecting code, although it's surely possible to identify them by manifest content or the presence of a signature.

If ever the ordinary interpreter files are signed (i.e. with a publicly trusted certificate), the compiler would probably need to be updated to strip out the signature.  So there's probably no use for actually detecting a signature at this point.

**Comment by TAC109** [comment]
Excluded by name as requested.
