### ISSUE TITLE
1.1.34.02 the bold style of "Convert" seems a little bit ugly

### ISSUE THREAD

**Issue by iesvme** [AutoHotkey/Ahk2Exe#89]
![无标题](https://user-images.githubusercontent.com/16969250/170802365-f4e877e1-61e3-41c2-bf81-e3ebaf924a22.png)

**Comment by TAC109** [comment]
What font are you using?

**Comment by iesvme** [comment]
I use Chinese win10 1809 system. The system default font is "simsun".

**Comment by TAC109** [comment]
This will be fixed in the next release.

**Comment by iesvme** [comment]
Thank you very much!
