### ISSUE TITLE
Possibly use SVG logo instead of PNG

### ISSUE THREAD

**Issue by joedf** [AutoHotkey/Ahk2Exe#91]
Instead of
```ahk
Gui, Add, Pic, x20 y6 w240 h78 vHeading1, %A_ScriptDir%\logo.png
```
We can use the following:
```ahk
; prevent IE-7 emulation mode - taken from Neutron.ahk by GeekDude
KEY_FBE := "HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BROWSER_EMULATION"
EXE_NAME := A_IsCompiled ? A_ScriptName : StrSplit(A_AhkPath, "\").Pop()
RegRead, fbe, % KEY_FBE, % EXE_NAME
RegWrite, REG_DWORD, % KEY_FBE, % EXE_NAME, 0

; now, add the web control
Gui, Add, ActiveX, x0 y1 w250 h80 vHeading1, about:blank
; we should simply include the SVG as a string, here. FileRead is used to shorten this example...
; https://www.autohotkey.com/static/ahk_logo_no_text.svg
FileRead, SVGLOGO, %A_ScriptDir%\logo.svg

; get the default GUI color, to hide the default white background from IE control
;https://www.autohotkey.com/board/topic/79600-how-to-get-default-gui-color/#entry505635
DefaultGUIColor := Format("#{1:X}", DllCall("User32.dll\GetSysColor", "Int", COLOR_3DFACE:=15, "UInt"))

; insert the html with SVG logo
wb:=Heading1, doc:=wb.Document
doc.write("<!DOCTYPE html><html><head><meta http-equiv='X-UA-Compatible' content='IE=edge'></head><body style=""margin:0 0 0 -4px;padding:0;background: " . DefaultGUIColor . """>" . SVGLOGO . "</body></html>")
doc.close()

; set the appropriate zoom according to DPI/System UI scaling
wb.ExecWB( OLECMDID_OPTICAL_ZOOM := 63, OLECMDEXECOPT_DONTPROMPTUSER := 2, (100*A_ScreenDPI*A_ScreenDPI/(96*96)) & 0xFFFFFFFF, 0)
```

I've tested this on my 4k screen laptop to fit almost exactly where is original is. So no more pixelated logo. Of course the alternative is just to use larger resolution for the `logo.png` file.... Thoughts?

<details>
<summary><b>Screenshots</b></summary>

## Before:
<img src="https://user-images.githubusercontent.com/3848219/189506761-7e8d16ec-b0a5-4b28-8001-befbe0c15553.png" width="600">

## After:
<img src="https://user-images.githubusercontent.com/3848219/189506764-157a3740-8e0f-4e28-b978-f1bb103c3c49.png" width="600">
</details>

**Comment by joedf** [comment]
@TAC109

**Comment by TAC109** [comment]
@joedf Certainly looks sharper in your screenshots, although my computer has dpi of 200% and the current logo looks good on that.

The patch looks like it is writing to the registry. Is this ok on user's machines?
What about in the .exe? (Currently there is GDI+ code executed in the compiled Ahk2Exe.)
Is this change compatible with earlier versions of Windows such as XP? 
Also how does it look in dark mode?

Cheers

**Comment by joedf** [comment]
I am only on windows 10. I am dark mode, but not style change apparently...  I think there is an alternative to the Registry changes... We can look for them later. I used it here to get it working and see what it looks like.

I am on 3840x2400 with 225% scaling. After some quick seraching, it looks like it will not be compatible with XP since it only supports IE <= 8... <strike>However, I thought Windows 7 is now the minimum supported Windows version, no?</strike>
We could keep the PNG for windows XP and below.

I pushed it into a branch just now. Perhaps you could give it a try?
https://github.com/joedf/Ahk2Exe/tree/feature-91-svg_logo

If it works well for you, I can initiate the PR and then edit it with improvements such as avoiding the registry, etc.

**Comment by TAC109** [comment]
@joedf 
Could you investigate further the larger resolution for the existing logo.png file, as you suggested in your first post?

**Comment by joedf** [comment]
https://github.com/joedf/Ahk2Exe/tree/2x-logo-resolution
Looks better, but in compiled, the `GuiControl, Move, %hPicCtrl%, w240 h77` cause it to pixelate a bit. 😓
<details>
<summary><b>Screenshots</b></summary>

## Not compiled
![image](https://user-images.githubusercontent.com/3848219/189532765-951c0666-52fa-45bc-a1b8-4a162504a80f.png)

## Compiled
![image](https://user-images.githubusercontent.com/3848219/189533187-224d3161-f6c5-4b3d-8208-91ac4e2684d0.png)
</details>

**Comment by TAC109** [comment]
I am happy with the look of the 2x png in the compiled .exe, and see it as a definite improvement on the existing logo. I would be happy for this to be included.

Does this suit you?

**Comment by joedf** [comment]
Agreed, please feel free to merge this:
https://github.com/AutoHotkey/Ahk2Exe/pull/92

I've left it open in case there's anything else you might want to add.

**Comment by TAC109** [comment]
Just a note on the svg proposal in case of future reference: There is additional code in neuron.ahk which resets the registry back to what it was before the change. This could be included in the patch if this idea is ever resurrected later.

I’ll merge #92 soon.

Cheers
