### ISSUE TITLE
Update function assigns incorrect permissions

### ISSUE THREAD

**Issue by Lexikos** [AutoHotkey/Ahk2Exe#93]
Files installed by the Ahk2Exe update function have "full control" permissions assigned to the current user, in addition to whatever permissions are inherited from the parent directory. This allows programs which are not running as administrator to write to these files. In theory, this is a security vulnerability.

My guess would be that the updater is downloading to a temporary directory to which the current user has write permission, and then using FileMove, which retains the permissions of the source file. (By contrast, creating a temporary directory under the installation directory would ensure both the temporary files and the final files have the same set of permissions as the rest of the installation.)

**Comment by TAC109** [comment]
Good guess! 

I’ll make the suggested change.

**Comment by TAC109** [comment]
Although I’ve been aware that sometimes I don’t need administrator privileges to update Ahk2Exe in the `Program Files\AutoHotkey\Compiler` directory I hadn’t realised why until now.

I’ve looked at the security tab of the properties window but I can’t see anything different, comparing the borked Ahk2Exe.exe with say AutoHotkey.exe. Can you explain the difference in more detail?

The current method has the advantage that the preliminary check for updates doesn’t need administrator privileges. Can the faulty security on Ahk2Exe etc be fixed programmatically?

I’ve done some 'drag and drop' testing and it seems that once `Program Files\AutoHotkey\Compiler\Ahk2Exe.exe` gets the undesirable permissions, they persist on the updated Ahk2Exe.exe. Is there going to be a problem reverting the permissions to the correct state?

Cheers

**Comment by Lexikos** [comment]
> The current method has the advantage that the preliminary check for updates doesn’t need administrator privileges.

The "preliminary check for updates" involves actually downloading **all** of the files? That is **not** what I expect "*check* for updates" to do. Don't do that. I don't even have or want mpress installed. 4 MB may not seem like much to some people, but it is a lot more than necessary to check a few version numbers.

By contrast, I upload (via script) the current AutoHotkey 1.1 and 2.0 version numbers so that they can be retrieved with a simple HTTP query. This obviously doesn't require administrator privileges.

> Can the faulty security on Ahk2Exe etc be fixed programmatically?

Sure, but it's generally more complicated than I bother with. The simplest way is probably to use the `icacls` command line tool.

I wouldn't be concerned about fixing it programmatically. Just don't mess it up in the first place. For one thing, if you mess it up and then fix it, there is a window during which other programs can modify the file. It's also possible that the admin intentionally alters the permissions.

> I’ve looked at the security tab of the properties window but I can’t see anything different,

I noticed it because Ahk2Exe.exe and upx.exe were showing a "padlock" icon overlay. I don't know why. This was on my laptop, on which I have been regularly uninstalling and installing AutoHotkey for testing purposes. I have just reinstalled v1.1.34.04 and updated Ahk2Exe, and there is no padlock.

The difference in the Security tab between Ahk2Exe.exe and its parent directory (or other files) after using the update function is *very* noticeable.
  - The parent directory inherits from Program Files, and as such has permissions for ALL APPLICATION PACKAGES, ALL RESTRICTED APPLICATION PACKAGES, CREATOR OWNER, SYSTEM, Administrators, Users and TrustedInstaller. If I select any of these items, the tick-marks under Allow are grey, showing they are *inherited*.
  - Ahk2Exe has **only** SYSTEM, *%USERNAME%* and Administrators. *%USERNAME%* has full control. The tick-marks are black, showing they are explicit permissions, not inherited. These permissions are identical to those that would be inherited from %TEMP%.

This is because when you use FileMove to move a file between locations on the same volume, the file's access control lists (permissions) are left untouched.

If you instead use FileCopy, I believe the new files will inherit the permissions of the parent directory.

**Comment by TAC109** [comment]
> The "preliminary check for updates" involves actually downloading all of the files? ...

They are downloaded into a temp directory, which is deleted at the end of the update process.

The main reason I adopted this approach was to obtain the new version number of UPX.exe, which is not obtainable by other means, as far as I know. It was convenient to handle obtaining the version numbers of the other items the same way.

> > I’ve looked at the security tab of the properties window but I can’t see anything different,
> 
> I noticed it because Ahk2Exe.exe and upx.exe were showing a "padlock" icon overlay. ...

Sorry, I rechecked this and indeed, the permissions tab looks quite different. Obviously finger trouble at my end!
> This is because when you use FileMove to move a file between locations on the same volume, the file's access control lists (permissions) are left untouched.
> 
> If you instead use FileCopy, I believe the new files will inherit the permissions of the parent directory.

I've tested this using the Copy command and I've confirmed that the permissions are now correct. However, I have discovered that it is necessary to delete the old file to be updated first.

This fix is in eb4cda1.

Cheers

**Comment by joedf** [comment]
Can we consider this resolved now?

**Comment by TAC109** [comment]
Closed
