### ISSUE TITLE
Cancelling elevation of the update function shows an error

### ISSUE THREAD

**Issue by Lexikos** [AutoHotkey/Ahk2Exe#94]
If the update function shows an elevation prompt (`Run *RunAs`) and then the user cancels it, a standard "Failed attempt to launch program or document" error message is shown. I would suggest handling specifically the "cancel" error to suppress this message. For example:
```AutoHotkey
try
    Run *RunAs notepad
catch e
    if !InStr(e.Extra, "cancel")  ; This is the *localized* error message.
        throw e
```
Alternatively, if you use `UseErrorLevel`, `A_LastError` will be 1223 (ERROR_CANCELLED) if the user cancelled; but then other errors won't give a detailed error dialog unless you implement that.

**Comment by TAC109** [comment]
Closed by commit 0aebfdc

Thanks for reporting.
