### ISSUE TITLE
#Include files with quoted filenames are not found, causing compile failure

### ISSUE THREAD

**Issue by SandyClams** [AutoHotkey/Ahk2Exe#95]
using Win 7 with Ahk2Exe v1.1.34.04b

**Comment by TAC109** [comment]
Could you supply a short example script plus a simple #Include file demonstrating the problem, please.

Cheers

**Comment by SandyClams** [comment]
X:\example.ahk
```
; compilation fails when any of these lines are uncommented
; #Include 'include.ahk'
; #Include '.\include.ahk'
; #Include 'X:\include.ahk'
; #Include "include.ahk"
; #Include ".\include.ahk"
; #Include "X:\include.ahk"
```

X:\include.ahk
```
```

**Comment by TAC109** [comment]
I also should have asked; what is the name of the base file you are using, and the exact text of the error message (you can copy the error message with ctrl+c [ignore the 'ding'] and past it into your reply).

Thanks

**Comment by SandyClams** [comment]
my base file is recognized in the Ahk2Exe GUI by the title `v2.0-beta. 12 U64 AutoHotkey64.exe`, the executable is titled `AutoHotkey64.exe`. The full text of the error popup says,

> #include file cannot be opened.

> Specifically:
"X:\\'include.ahk'"

where the text `'include.ahk'` is replaced in the same manner with the full quoted string value from the first uncommented line in the script, including for the lines where the value is the absolute path.

**Comment by SandyClams** [comment]
awesome, glad to hear it  :D
