### ISSUE TITLE
Curiosity on the version requirements that seem hard-coded into FindBinsExes

### ISSUE THREAD

**Issue by Nackloose** [AutoHotkey/Ahk2Exe#98]
Just a simple question, maybe an issue?
> [Jump to answer](https://github.com/AutoHotkey/Ahk2Exe/issues/98#issuecomment-1621764314)

Both https://github.com/AutoHotkey/Ahk2Exe/blob/63ce73a8bfda90d509b598641ddbebc65f9bed62/Ahk2Exe.ahk#L310-L312 and https://github.com/AutoHotkey/Ahk2Exe/blob/63ce73a8bfda90d509b598641ddbebc65f9bed62/Lib/AHKType.ahk#L14-L17 are doing some version checking on the file we are iterating.

There is the 'era' check if you will, and then a hard coded check that doesn't seem to allow below 1.34
The era check I understand whole heartedly, however the other, there is no comments or any documentation I can find as to maybe why.

I am translating the function as well as AHKType into python and just want to make sure as to the reasoning here. (And if I maybe need to hot-swap versions of Ahk2Exe)
After doing so I realized that the version of ahk (1.27.x.x) SC.bin that I had, wasn't being read after porting the function.

Just found myself a little confused that the era check is checking for before 1.1, yet the FindExesBins is expecting higher than 1.34. Not sure if it was intentional, and wanted to understand what's happening.

Is that just because 1.34 is the last AHK 1.0 release? Or is there some incompatibility with the current codebase of Ahk2Exe with previous versions and this is why its hard coded?
 
 Or maybe I fundamentally mis-undestood something entirely.
 
Thanks a bunch!

**Comment by TAC109** [comment]
There are two main v1 AutoHotkey versions; 1.0 and 1.1. The last version of v1.0 was 1.0.48.05 published back in September 2009, and it has its own version of Ahk2Exe. The current v1.1 Ahk2Exe cannot be used to compile v1.0 scripts and that is why AHKType.ahk has the check quoted.

Regarding AutoHotkey v1.1 and v2, an enhancement was included in versions 1.1.34.00 and 2.0-a135 which allowed AutoHotkey*.exe files to be used as base files, in addition to *.bin files. Prior to these versions only *.bin base files could be used for compilation. The Ahk2Exe.ahk quoted code is checking that the selected *.exe file meets this criteria. 

On reflection I see that the v1.1 and v2 checks should be enhanced in Ahk2Exe.ahk to include the sub-version in light of future planned enhancements to v2.

Regarding hot swapping Ahk2Exe, this should only be needed if you intend to support Ahk2Exe v1.0. The latest version of Ahk2Exe v1.1 should always be the most bug free, and I’m usually prompt in fixing any bugs found.

Cheers

**Comment by Nackloose** [comment]
Thanks so much for your swift reply! Assuming I understand correctly this makes perfect sense.

I shouldn't even need to support anything below the newest 1.x version as it shouldn't change an all 1.x scripts as a whole should be supported by it, correct?

I really appreciate the informative response!

**Comment by TAC109** [comment]
Yes, the latest version of Ahk2Exe can compile all v1.1.xx.xx scripts.

Cheers

**Comment by TAC109** [comment]
I’ll add something to the code.

Thanks
