### ISSUE TITLE
Could not move final compiled binary file to destination(C1)

### ISSUE THREAD

**Issue by abgox** [AutoHotkey/Ahk2Exe#99]
- **I was able to compile normally until I reinstalled the Windows system**
- **Now an empty file cannot be compiled**

<img width="474" alt="Snipaste_2023-08-21_12-19-20" src="https://github.com/AutoHotkey/Ahk2Exe/assets/131574323/8095f031-6696-4072-840c-e142475626ac">

**Comment by TAC109** [comment]
There was a bug in Ahk2Exe v1.1.37.01a which I have just fixed in v1.1.37.01b. 

Cheers
